version: '3.8'

services:
  # admin:
  #   image: toi-mua-sach/admin
  #   build: client_admin
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 3001:3001
  #   depends_on:
  #     - server

  # client:
  #   image: toi-mua-sach/client
  #   build: client
  #   environment:
  #     NODE_ENV: production
  #   ports:
  #     - 3000:3000
  #   depends_on:
  #     - server

  server:
    image: toi-mua-sach/server
    build: server
    env_file:
      - ./server/.env
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
