export const ADD_BOOK_TO_CART = 'add-book-to-cart'
export const SELECT_ALL_BOOK_IN_CART = 'select-all-book-in-cart'
export const UPDATE_BOOK_IN_CART ='update-book-in-cart'
export const REMOVE_BOOK_IN_CART = 'remove-book-in-cart'
export const LOGIN_BY_USER = 'login-by-user'
export const SELECT_CATEGORY = 'select-category'
export const SELECT_CATEGORY_CHILD = 'select-category_child'