const first = [
	{
		_id: "634ed8e4f6a3a7266d992770",
		name: "Công Chúa Ma Cà Rồng Quyền Năng Chỉ Muốn Có Một Người Em Gái Mà Thôi",
		description:
			'Công Chúa Ma Cà Rồng Quyền Năng Chỉ Muốn Có Một Người Em Gái Mà Thôi\nĐã từ lâu, trên lục địa Ephenia tồn tại một bộ tộc ma cà rồng đáng sợ có tên là "Thuần huyết", những người sở hữu sức mạnh phi thường, cho phép họ thống trị tất cả các bộ tộc khác. Tuy nhiên, một thiên niên kỷ đã trôi qua và mọi dấu vết của họ đã hoàn toàn biến mất khỏi hành tinh, cho đến khi hậu duệ trẻ nhất và tài năng nhất của Thuần huyết thức tỉnh ở thời hiện đại.\nCông chúa ma cà rồng Ristia chỉ có khao khát duy nhất - một cô em gái dễ thương! Vô cùng mạnh mẽ, giỏi phép thuật và xinh đẹp động lòng người, ai ai cũng coi cô ấy như một “thiên thần”, nhưng cô ấy khẳng định với mọi người rằng mình chỉ là một cô gái bình thường. Liệu “cô gái bình thường" này có thể tìm thấy cô em gái như khao khát của cô ấy không?\nHãy cùng theo dấu ma cà rồng (bất thường) này thông qua một cuộc phiêu lưu tìm kiếm người em gái trong tưởng tượng nhé!\n- Quà tặng Kèm :\n* Bản thường: 1 postcard bồi cứng in 2 mặt\n* Bản đặc biệt: 1 postcard bồi cứng in 2 mặt + 1 huy hiệuGiá sản phẩm trên ToiMuaSach đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....',
		translators: "Như Nữ",
		isbn13: "",
		supplier: "USAGI LIGHT NOVEL",
		publisher: "Nhà Xuất Bản Phụ Nữ",
		publishDate: "2022-08-31T17:00:00.000Z",
		images: [
			"https://salt.tikicdn.com/ts/product/3e/3d/b8/d198f35a0cd0bb96dbe43abd966af720.jpg",
			"https://salt.tikicdn.com/ts/product/45/2f/3c/890efbfdfa006076f5fdb4138ab3394f.jpg",
			"https://salt.tikicdn.com/ts/product/b4/8c/7d/90fb5049d9c7d3b429c65be053dc23f9.jpg",
			"https://salt.tikicdn.com/ts/product/1a/62/c9/db902d0ed6618d4c6517900d929afa67.jpg",
			"https://salt.tikicdn.com/ts/product/e7/34/5a/a161ea448f67f3a96ae25beba280201d.jpg",
		],
		page: null,
		bookCover: "Bìa mềm",
		status: "available",
		originalPrice: 175000,
		discountRate: 21,
		category: {
			_id: "634d8da516d1688abe54d4ef",
			id: "634d8da516d1688abe54d4ef",
			name: "Light novel",
		},
		createdAt: "2022-10-18T16:48:37.080Z",
		updatedAt: "2022-11-23T01:57:15.147Z",
		slug: "cong-chua-ma-ca-rong-quyen-nang-chi-muon-co-mot-nguoi-em-gai-ma-thoi",
		sold: 99,
		price: 138000,
		countInStock: 5401,
		id: "634ed8e4f6a3a7266d992770",
	},
	{
		_id: "634ed8e4f6a3a7266d9927b2",
		name: "Chuyện Tình Thanh Xuân Bi Hài Của Tôi Quả Nhiên Là Sai Lầm 6.5",
		description:
			"Chuyện tình thanh xuân bi hài của tôi quả nhiên là sai lầm. (tên gốc: Yahari Ore no Seishun Rabukome wa Machigatteiru., gọi tắt là Oregairu), là một trong những series light novel ăn khách nhất trong vòng 20 năm trở lại đây, bộ truyện được viết bởi tác giả trẻ Wataru WATARI, do họa sĩ Ponkan8 vẽ minh họa và được xuất bản bởi NXB nổi tiếng Shogakukan.\nChuyện tình thanh xuân bi hài của tôi quả nhiên là sai lầm. đã dành giải light novel hay nhất của bảng xếp hạng uy tín Kono light novel ga sugoi! trong 3 năm liên tiếp là 2014, 2015 và 2016. Bên cạnh đó, nam chính và nữ chính của series này là Hachiman và Yokin oshita cũng đoạt giải nam nữ chính được yêu thích nhất trong các năm đó. Họa sĩ minh họa Ponkan8 với những bức tranh minh họa đẹp và sinh động của mình cũng được bình chọn là họa sĩ minh họa được yêu thích nhất trong năm 2015. Đến thời điểm hiện tại, series đã kết thúc với 14 tập, nhưng số sách bán ra đã vượt mốc 10 triệu bản.\nLễ hội văn hoá kết thúc với những dư vị đắng ngắt! Hachiman trở thành cái gai trong mắt toàn trường, còn Sagami thì ngày càng trở nên phiền phức hơn. Bầu không khí trong lớp học trở nên tồi tệ, điều ấy đã khiến “nữ vương” cảm thấy chướng mắt.\nĐồng thời, cô Hiratsuka cũng nảy ra ý tưởng về hòm tư vấn email xuyên tỉnh Chiba, giao cho CLB Tình nguyện xử lý những yêu cầu tư vấn tâm lý trực tuyến trong phạm vi tỉnh Chiba. Hachiman lại ngập đầu trong công việc. Nhưng đấy chưa phải là tất cả!\nChị hội trưởng Shiromeguri Meguri xuất hiện tại phòng CLB để gửi yêu cầu cùng tổ chức một hội thao đáng nhớ. Tuy nhiên, dù rất sát thời gian hội thao diễn ra nhưng vị trí trưởng Ban tổ chức vẫn khuyết. Cùng lúc ấy, một yêu cầu mới được gửi tới CLB Tình nguyện về trường hợp của Sagami. Yukinoshita, Yui và Hachiman đã quyết định sẽ thuyết phục Sagami tiếp tục đảm nhiệm vai trò Trưởng Ban tổ chức hội thao, một mũi tên trúng hai đích.\nVậy nhưng, rắc rối nảy sinh đến từ nh���ng nhân vật không ngờ, khiến cho quá trình chuẩn bị bị trễ nải rất nhiều. Những cô cậu ấy sẽ thành công vượt qua thử thách và trưởng thành hơn, hay sẽ bị tụt dốc bởi những sai lầm của tuổi thanh xuân?\nTập 6.5 “Vậy nên, lễ hội của họ vẫn chưa kết thúc” đi kèm với Bonus track “Khi ánh nến Giáng sinh đung đưa lay động” rất được mong chờ!\nVề tác giả:\nWataru WATARI\nSinh năm 1987. Nhóm máu A, cung Bảo Bình. Thường bị phê phán là dáng vẻ bận bịu và thiếu ngủ của mình khiến cho người khác rất khó chịu nhưng tôi có muốn thế đâu, phần lớn những lúc như vậy chỉ đơn thuần là tín hiệu SOS mà thôi. Tuy tinh thần tôi yếu ớt nhưng thể lực tôi lại mạnh mẽ đến mức thừa thãiPonkan 8\nĐến mùa nằm dưới bàn sưởi ăn kem rồi\nBố cục sách:\nChương 1: Một lần nữa, cô Hiratsuka lại đưa ra mệnh lệnh mới\nChương 2: Bây giờ, chúng tôi lại tình cờ gặp chị Shiromeguri Meguri\nChương 3: Đúng như dự đoán, Sagami Minami vẫn chẳng thay đổi gì cả\nChương 4: Yukinoshita Yukino vẫn tiếp tục thử đi thử lại đến cùng\nChương 5: Từ những điều đã xảy ra, Hikigaya Hachiman có linh cảm\nChương 6: Kể cả như vậy, Shiromeguri Meguri vẫn đang dõi theo\nChương 7: Và rồi, cuộc họp cuối cùng được tiến hành thật thuận lợi\nChương 8: Vậy nên, lễ hội của họ vẫn chưa kết thúc\nLời bạt (Giữa truyện)\nBonus Track! Khi ánh nến Giáng sinh đung đưa lay động…Giá sản phẩm trên ToiMuaSach đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
		translators: "AQ",
		isbn13: "",
		supplier: "Thái Hà",
		publisher: "Nhà Xuất Bản Hà Nội",
		publishDate: "2020-06-30T17:00:00.000Z",
		images: [
			"https://salt.tikicdn.com/ts/product/a5/dd/4b/a20f2f08d9faf09fd723b2f2d4ff6cfb.jpg",
		],
		page: null,
		bookCover: "Bìa mềm",
		status: "available",
		originalPrice: 179000,
		discountRate: 15,
		category: {
			_id: "634d8da516d1688abe54d4ef",
			id: "634d8da516d1688abe54d4ef",
			name: "Light novel",
		},
		createdAt: "2022-10-18T16:48:37.081Z",
		updatedAt: "2022-11-23T01:57:15.150Z",
		slug: "chuyen-tinh-thanh-xuan-bi-hai-cua-toi-qua-nhien-la-sai-lam-6-5",
		sold: 99,
		price: 152000,
		countInStock: 1401,
		id: "634ed8e4f6a3a7266d9927b2",
	},
	{
		_id: "634ed8e4f6a3a7266d9927f6",
		name: "Liệu Có Sai Lầm Khi Tìm Kiếm Cuộc Gặp Gỡ Định Mệnh Trong Dungeon? – Tập 7",
		description:
			"Dungeon không phải lúc nào cũng là nơi tăm tối nhất! \nSau trận War Game, Hestia familia thu nhận thêm ba thành viên mới là Lili, Welf và Mikoto. Giờ họ đã trở thành gia đình thứ hai của Bell, gắn kết sâu sắc với cậu. Hestia familia non trẻ bắt đầu có những bước tiến đầu tiên! \nTrong lúc đuổi theo Mikoto tới khu giải trí của Orario, Bell lạc vào khu phố đêm nằm dưới quyền quản lí của Ishtar familia. Tại nơi này, cậu thiếu niên tình cờ gặp thiếu nữ tên Haruhime xuất thân vùng Viễn Đông đang bị giam cầm. \nBị cuốn vào vòng xoáy âm mưu hiểm độc giữa các nữ thần, Bell buộc phải đưa ra sự lựa chọn. Với cậu, “anh hùng” thật sự là như thế nào? \n“Nếu cậu trở thành anh hùng của cô ấy thì mọi chuyện sẽ ổn thôi, phải không?” \nĐây là câu chuyện do cậu thiếu niên tạo, nữ thần viết. \n* LIỆU CÓ SAI LẦM KHI TÌM KIẾM CUỘC GẶP GỠ ĐỊNH MỆNH TRONG DUNGEON? là series light-novel nổi tiếng của tác giả Fujino Omori. Bộ truyện đã bán ra hơn 12 triệu bản tại Nhật Bản, và là nguyên tác của loạt phim anime cùng các game ăn khách!\n---\nMột ấn phẩm của WINGS BOOKS - Thương hiệu sách trẻ của NXB Kim Đồng.Giá sản phẩm trên ToiMuaSach đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
		translators: "Dekoboko",
		isbn13: "",
		supplier: "Wings Books",
		publisher: "Nhà Xuất Bản Kim Đồng",
		publishDate: "2022-02-01T17:00:00.000Z",
		images: [
			"https://salt.tikicdn.com/ts/product/32/73/55/a21fc82e7d18809bf81685b44a4ba5f7.jpg",
			"https://salt.tikicdn.com/ts/product/d0/dd/fd/1337b5776306f834d0672b4a1d800be3.jpg",
		],
		page: null,
		bookCover: "Bìa mềm",
		status: "available",
		originalPrice: 150000,
		discountRate: 18,
		category: {
			_id: "634d8da516d1688abe54d4ef",
			id: "634d8da516d1688abe54d4ef",
			name: "Light novel",
		},
		createdAt: "2022-10-18T16:48:37.082Z",
		updatedAt: "2022-11-23T01:57:15.153Z",
		slug: "lieu-co-sai-lam-khi-tim-kiem-cuoc-gap-go-dinh-menh-trong-dungeon-tap-7",
		sold: 99,
		price: 123000,
		countInStock: 1401,
		id: "634ed8e4f6a3a7266d9927f6",
	},
	{
		_id: "634ed8e5f6a3a7266d992868",
		name: "Fate/Zero 5 - Mạch Ngầm Bóng Tối",
		description:
			"Cuộc chiến Chén Thánh lần IV đang đến hồi cao trào.\nGiữa muôn trùng thủ đoạn của Emiya Kiritsugu và những hành động trong bóng tối của Kotomine Kirei, các anh linh và pháp sư lần lượt bỏ mạng…\nỞ cuối cuộc tử chiến cam go, Saber chuẩn bị phải đối đầu với địch thủ đáng gờm là vua chinh phạt Iskandar.\nCưỡi chiếc VMAX cải tiến vọt qua khe hở hẹp để sang “phía bên kia”, liệu Saber có cơ hội chiến thắng?\nPhần truyện ở ranh giới cuối cùng này là tập 5 của câu chuyện dẫn về khởi điểm!Giá sản phẩm trên ToiMuaSach đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
		translators: "",
		isbn13: "",
		supplier: "IPM",
		publisher: "Nhà Xuất Bản Hồng Đức",
		publishDate: "2019-11-30T17:00:00.000Z",
		images: [
			"https://salt.tikicdn.com/ts/product/99/77/b3/8f85b8617bfb87f47ccfc8f6e1c8c1bd.jpg",
		],
		page: null,
		bookCover: "Bìa mềm",
		status: "available",
		originalPrice: 90000,
		discountRate: 15,
		category: {
			_id: "634d8da516d1688abe54d4ef",
			id: "634d8da516d1688abe54d4ef",
			name: "Light novel",
		},
		createdAt: "2022-10-18T16:48:37.084Z",
		updatedAt: "2022-11-23T01:57:15.156Z",
		slug: "fate-zero-5-mach-ngam-bong-toi",
		sold: 99,
		price: 77000,
		countInStock: 8401,
		id: "634ed8e5f6a3a7266d992868",
	},
	{
		_id: "634ed8e5f6a3a7266d9928c2",
		name: "Miền Đất Hứa - The Promised Neverland - Khúc Ca Xưa Của Isabella Và Krone - Tặng Kèm 1 Pop-up Card (Thiết Kế Độc Quyền Cho Phiên Bản Việt Nam)",
		description:
			"\n \n \n Miền Đất Hứa - The Promised Neverland - Khúc Ca Xưa Của Isabella Và Krone - Tặng Kèm 1 Pop-up Card (Thiết Kế Độc Quyền Cho Phiên Bản Việt Nam)\n \nGiá sản phẩm trên ToiMuaSach đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
		translators: "",
		isbn13: "",
		supplier: "IPM",
		publisher: "Nhà Xuất Bản Hà Nội",
		publishDate: "2022-10-18T16:48:37.027Z",
		images: [
			"https://salt.tikicdn.com/ts/product/3b/bd/9d/512895271ae176a6f63ed642aea58d3c.jpg",
			"https://salt.tikicdn.com/ts/product/fa/fc/ed/ae79693424b64cac3f60f623120b8de6.jpg",
		],
		page: null,
		bookCover: "",
		status: "available",
		originalPrice: 70000,
		discountRate: 15,
		category: {
			_id: "634d8da516d1688abe54d4ef",
			id: "634d8da516d1688abe54d4ef",
			name: "Light novel",
		},
		createdAt: "2022-10-18T16:48:37.086Z",
		updatedAt: "2022-11-23T01:57:15.157Z",
		slug: "mien-dat-hua-the-promised-neverland-khuc-ca-xua-cua-isabella-va-krone-tang-kem-1-pop-up-card-thiet-ke-doc-quyen-cho",
		sold: 99,
		price: 60000,
		countInStock: 1401,
		id: "634ed8e5f6a3a7266d9928c2",
	},
	{
		_id: "634ed8e5f6a3a7266d9928ad",
		name: "Lời Nói Đùa 2 - Kẻ Siết Cổ Mộng Mơ (Zaregoto) (Kèm Quà Tặng Số Lượng Có Hạn)",
		description:
			'Yêu một người thì dễ, nhưng tiếp tục yêu họ thì khó. Cũng giống như giết người thì dễ, nhưng tiếp tục giết người thì khó vậy. \nTrung thực và chân thành, sống đến từng này tuổi mà không hề biết đến khái niệm dối trá, dù trong bất cứ hoàn cảnh nào cũng không thể rời mắt khỏi sự thật… nói tóm lại đó có thể coi là tính cách bẩm sinh của “tôi”, người đã chạm trán con quỷ giết người mang tên Zerozaki Hitoshiki vào một ngày tháng Năm. Đó vừa là một cuộc tao ngộ, vừa là điều đương nhiên phải tới. Đó là một ý chí sắc lẻm, một nguyên lý nhọn hoắt, và cũng là một trò đùa như mũi dao. Ngoài ra “tôi” còn có một cuộc gặp gỡ nho nhỏ với những người bạn cùng lớp nữa, nhưng cái đó thì chẳng biết nói sao, tôi chẳng biết nên bắt đầu kể từ chỗ nào. Bởi vì, này nhé, thân là con người, “tôi” làm sao nỡ nói dối cơ chứ…\nTác phẩm đầu tay viết năm mười tám tuổi đã đoạt ngay giải thưởng Mephisto danh giá, đưa tên tuổi Nisio Isin đến với độc giả Light Novel Nhật Bản, trở thành nguồn cảm hứng cho hàng loạt tiểu thuyết gia trẻ tuổi trong suốt thập kỷ đó.\nVỀ TÁC GIẢ\nNisio Isin (sinh năm 1981) được mệnh danh là cây bút thiên tài trong làng Light Novel Nhật Bản với rất nhiều tác phẩm đình đám. Năm 2002 khi đang theo học đại học Ritsumeikan, Nisio Isin ra mắt với tác phẩm "Vòng xoáy chặt đầu", tập đầu tiên trong series Lời nói đùa, và đã giành giải Mephisto lần thứ 23 ở tuổi đôi mươi. Bộ truyện đã có gần 4 triệu bản được bán ra tại Nhật và nhiều năm liên tiếp lọt top 3 của bảng xếp hạng Kono Light Novel ga Sugoi!\nSau khi rời khỏi trường đại học, Nisio Isin làm việc cho nhà xuất bản nổi tiếng Kodansha, chuyên về các tạp chí dành cho các cây bút trẻ như Faust hoặc Pandora. Tháng 1 năm 2007, Nisio Isin ra mắt series Đao Ngữ dưới nhãn Kodansha Box, với tiến độ mỗi tháng một tập, tổng cộng 12 tập đã được xuất bản đều đặn trong vòng một năm.\nCác tiểu thuyết Đao ngữ, Lời nói đùa, Monogatari,  Medaka Box và Juni Taisei của ông đã được chuyển thể thành anime.\nTRÍCH ĐOẠN\nMỗi khi nghĩ về Zerozaki, tôi chỉ có thể lý giải cậu ta bằng một khái niệm duy nhất: “hình ảnh phản chiếu trên mặt nước”. Nếu không hiểu như vậy, có lẽ hành động diễn tả kẻ mất tư cách làm người ấy bằng ngôn từ cũng sẽ trở nên vô nghĩa mất thôi. Nhưng thay vì suy xét về hành động diễn tả, có lẽ câu hỏi chúng ta cần phải trả lời sẽ là: Vốn ngay từ đầu ở Zerozaki có tồn tại thứ gọi là “ý nghĩa” hay không? Giống như danh xưng “kẻ thích đùa” của tôi không mang một ý nghĩa nào cụ thể, đánh giá kẻ giết ngư��i ấy thông qua biểu hiện bên ngoài chẳng khác nào tin vào mấy bài giải mẫu đã bị sai lầm từ lâu. Nên diễn tả cảm giác ấy thế nào nhỉ? Tựa như đang đứng trước bản thể của chính mình, tựa như đang nói chuyện với chính bản thân mình, một câu chuyện với cốt truyện vừa kỳ quặc lại vừa hợp lý.\nPhải rồi.\nCho nên, ngay từ đầu đây đã là một cuộc gặp gỡ tình cờ bất khả thi.\nCó lẽ, đó là trải nghiệm nguyên sơ nhất.\nLà ngôn từ đầu tiên mà ta nghe thấy.\nLà những ghi chép vào bộ nhớ gốc.\nLà quá khứ ta có thể liên tưởng và so sánh.\nLà véc-tơ cùng gốc, cùng phương hướng.\nTựa như còn bình thường hơn cả bình thường.\nTựa như hình ảnh phản chiếu trên mặt gương.\nNói tóm lại, chúng tôi quá giống nhau.\nQuà tặng kèm:Bookmark giấy\nCard mica trong suốt 10x15cm (Số lượng giới hạn)\nMóc chìa khóa mica (số lượng giới hạn)\nGiá sản phẩm trên ToiMuaSach đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....',
		translators: "",
		isbn13: "",
		supplier: "Nhã Nam",
		publisher: "Nhà Xuất Bản Hội Nhà Văn",
		publishDate: "2020-03-31T17:00:00.000Z",
		images: [
			"https://salt.tikicdn.com/ts/product/62/0c/ca/a456cb4017a5f2c50769312e3721da8d.jpg",
		],
		page: null,
		bookCover: "Bìa mềm",
		status: "available",
		originalPrice: 175000,
		discountRate: 15,
		category: {
			_id: "634d8da516d1688abe54d4ef",
			id: "634d8da516d1688abe54d4ef",
			name: "Light novel",
		},
		createdAt: "2022-10-18T16:48:37.085Z",
		updatedAt: "2022-11-23T01:57:15.157Z",
		slug: "loi-noi-dua-2-ke-siet-co-mong-mo-zaregoto-kem-qua-tang-so-luong-co-han",
		sold: 99,
		price: 149000,
		countInStock: 5401,
		id: "634ed8e5f6a3a7266d9928ad",
	},
	{
		_id: "634ed8e5f6a3a7266d9928e2",
		name: "Cuộc Chiến Siêu Nhiên Giữa Đời Thường Tập 13",
		description:
			"Cuộc chiến siêu nhiên giữa đời thường – Tập 13\nTập cuối trong series Cuộc chiến siêu nhiên giữa đời thường, một series light novel hài hước học đường cực kì thú vị, nơi những thành viên trong câu lạc bộ văn học đột nhiên đến một ngày thức tỉnh siêu năng lực.\n“Một năm đã trôi qua kể từ trận chiến cuối cùng.\nTrận chiến khốc liệt giữa tôi và anh Kiryuu- trận quyết chiến đỉnh cao với Kiryuu Heldkaiser Luci First.\nTrận chiến đặt dấu chấm hết cho tất cả các câu chuyện từ trước đến nay ấy… thật khó để có thể mô tả được bằng lời.\nKhông bút mực nào có thể tả xiết.\nKhông câu văn nào có thể diễn đạt được nó,\nMà, nói tóm lại, một năm đã trôi qua kể từ khi đó,\nSau rất nhiều chuyện xảy ra- tôi bắt đầu hẹn hò với một cô gái”.\nKết cục của chiến tranh Tinh Linh và kết cục của câu chuyện tình yêu này liệu sẽ là gì?\nCùng đón đọc tập cuối cùng của “Cuộc chiến siêu nhiên giữa đời thường” để chào đón hồi kết của câu chuyện!Giá sản phẩm trên ToiMuaSach đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
		translators: "Suigyo",
		isbn13: "",
		supplier: "Sakurabooks",
		publisher: "Nhà Xuất Bản Phụ Nữ Việt Nam",
		publishDate: "2022-10-18T16:48:37.039Z",
		images: [
			"https://salt.tikicdn.com/ts/product/c0/54/6b/70e169688037f6481614aa21279a941c.jpg",
		],
		page: null,
		bookCover: "Bìa mềm",
		status: "available",
		originalPrice: 109000,
		discountRate: 22,
		category: {
			_id: "634d8da516d1688abe54d4ef",
			id: "634d8da516d1688abe54d4ef",
			name: "Light novel",
		},
		createdAt: "2022-10-18T16:48:37.086Z",
		updatedAt: "2022-11-23T01:57:15.158Z",
		slug: "cuoc-chien-sieu-nhien-giua-doi-thuong-tap-13",
		sold: 99,
		price: 85000,
		countInStock: 3401,
		id: "634ed8e5f6a3a7266d9928e2",
	},
	{
		_id: "634ed8e5f6a3a7266d992a99",
		name: "Lịch Sử Văn Học Thế Giới - Tập 2",
		description:
			"Nghiên cứu lịch sử văn học thế giới từ thế kỉ II đến đầu thế kỉ XIV, tức văn học thế giới từ sơ kỳ trung đại qua thịnh kỳ trung đại và chạm vào khởi đầu hậu kỳ trung đại.\nVới 10 chương, tập II của bộ sách là một bức tranh toàn cảnh văn học trung đại của nhiều vùng và nền văn học khác nhau: văn học Nam và Đông Nam Á, Văn học Đông và Đông Nam Á, văn học Tâm Á, văn học Cận Đông và Trung Á, văn học Kavkaz và ngoại Kavkaz, văn học vùng Byzance, văn học Trung và ��ông Nam Âu, văn học Nga cổ, văn học Tây Âu sơ kỳ trung đại, văn học Tây Âu thịnh kỳ.\nDựa trên góc nhìn so sánh và nhất quán với mục đích “vừa phải nói rõ qui luật phát triển của văn học các dân tộc, vừa phải nói rõ qui luật phát triển của văn học thế giới” (B. Riftin, Viện sĩ thông tấn, Viện Văn học thế giới mang tên Gorky, Lời tựa cho bản dịch tiếng Việt), các tác giả của bộ sách không chỉ miêu tả tiến trình phát triển của các nền và vùng văn học từ sơ kỳ trung đại đến đầu hậu kỳ trung đại, mà còn nỗ lực chỉ ra những tương đồng về hình thái văn học cũng như những tương tác giữa các vùng và nền văn học khác nhau trong sự phát triển lịch sử của chúng. Đặc biệt, dựa trên sự nghiên cứu hình thái kinh tế - xã hội, hình thái văn hóa – tư tưởng, phương thức sản xuất…, tập sách đã cung cấp những dữ kiện cần thiết, có tính gợi ý, giúp lí giải nhiều vấn đề của lịch sử văn học thế giới trung đại (trong đó gồm cả văn học Việt Nam), như: những chuyển động từ văn học cổ đại sang trung đại, những thay đổi mạnh m��� của văn học trung đại hậu kỳ, sự hình thành các hiện tượng văn học mới, nguồn gốc làm nảy sinh các thể loại văn học, tính chất không đồng đều trong tiến trình lịch sử văn học của các vùng và nền văn học khác nhau…\nHai tập của bộ sách Lịch sử văn học thế giới đã được chuyển ngữ tiếng Việt từ nguyên bản tiếng Nga bởi nhiều người dịch có uy tín gồm những dịch giả, những chuyên gia văn học nước ngoài tại các trường đại học (Đào Tuấn Ảnh, Trần Văn Cơ, Trần Thanh Đạm, Trịnh Bá Đĩnh, Lê Sơn, Trần Thị Phương Phương, Nguyễn Thị Thanh Tân, Nguyễn Thị Thu Thủy, Nguyễn Thị Như Trang, Lê Khánh Trường, Trần Hồng Vân) và được xuất bản bởi Trung tâm nghiên cứu quốc học và Nxb Văn học (tập 1 xuất bản năm 2008, tập 2 xuất bản năm 2012) là những phần rất quan trọng của một bộ sách quí, hết sức cần thiết đối với việc nghiên cứu văn học so sánh và lịch sử văn học cổ đại và trung đại. Hy vọng rằng những tập tiếp theo của bộ sách này sẽ sớm được chuyển ngữ sang tiếng Việt để ngưới đọc nói chung và giới nghiên cứu văn học nói riêng có cái nhìn bao quát hơn về bức tranh toàn cảnh văn học thế giới.Giá sản phẩm trên ToiMuaSach đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
		translators: "",
		isbn13: "",
		supplier: "Trung Tâm Nghiên Cứu Quốc Học",
		publisher: "Nhà Xuất Bản Văn Học",
		publishDate: "2012-01-01T06:19:36.000Z",
		images: [
			"https://salt.tikicdn.com/ts/product/67/30/ca/94b3f2a89e617457db7d376a3b5be580.jpg",
			"https://salt.tikicdn.com/ts/product/77/48/65/20ed730334c8b501a7500f1b052a8408.jpg",
			"https://salt.tikicdn.com/ts/product/07/c5/11/6f27d367a7a41c15826ece0010ea8994.jpg",
			"https://salt.tikicdn.com/ts/product/bb/5a/15/af97d3b30a598364929420a521c905bb.jpg",
		],
		page: null,
		bookCover: "Bìa cứng",
		status: "available",
		originalPrice: 350000,
		discountRate: 0,
		category: {
			_id: "634d8da516d1688abe54d4f0",
			id: "634d8da516d1688abe54d4f0",
			name: "Phê Bình - Lý Luận Văn Học",
		},
		createdAt: "2022-10-18T16:48:37.435Z",
		updatedAt: "2022-11-23T01:57:15.159Z",
		slug: "lich-su-van-hoc-the-gioi-tap-2",
		sold: 99,
		price: 350000,
		countInStock: 6401,
		id: "634ed8e5f6a3a7266d992a99",
	},
	{
		_id: "634ed8e5f6a3a7266d992b0a",
		name: "Nho Giáo",
		description:
			"Nho giáo của Trần Trọng Kim là một trong những bộ sách đầu tiên ở Việt Nam thời hiện đại nghiên cứu về Nho giáo Trung Hoa và những ảnh hưởng lớn lao của nó đến đời sống văn hóa Việt Nam. Không giấu giếm niềm ngưỡng mộ đối với một học thuyết từng là bệ đỡ tinh thần cho nhiều dân tộc Á Đông suốt hàng nghìn năm, Trần Trọng Kim đã tổng thuật và chứng minh tính hoàn chỉnh của một hệ thống triết học ở Nho giáo. Bằng phương pháp làm việc cẩn chỉ và nghiêm túc, Trần Trọng Kim đã đứng vững trên tư cách một nhà khoa học để thăm dò, miêu tả học thuyết phức tạp này, kể từ thời điểm nó ra đời, qua quá trình phái sinh, mở rộng bởi vô số học phái ở nhiều thời kỳ khác nhau, cho đến khi nó suy tàn vào đầu thế kỷ XX. Với việc cung cấp lượng tri thức uyên bác, khả tín, và bằng một văn phong giản dị, kết cấu mạch lạc, bộ sách của Lệ Thần Trần Trọng Kim là một công trình khảo cứu quyền uy và được tham khảo rộng rãi trong các nghiên cứu về Nho giáo ở Việt Nam.Ngày nay, những tranh luận về Nho giáo vẫn chưa khi nào bớt gay gắt và quyết liệt. Nhưng, dù khen hay chê Nho giáo, thì công trình của Trần Trọng Kim vẫn xứng đáng là cuốn sách nhập môn cho tất cả những ai muốn đi sâu và xa hơn để tìm hiểu học thuyết này.Giá sản phẩm trên ToiMuaSach đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
		translators: "",
		isbn13: "",
		supplier: "Nhã Nam",
		publisher: "Nhà Xuất Bản Thế Giới",
		publishDate: "2019-01-06T17:00:00.000Z",
		images: [
			"https://salt.tikicdn.com/ts/product/35/3c/9c/257f63336d366bfac9596399085cd0af.JPG",
		],
		page: null,
		bookCover: "Bìa mềm",
		status: "available",
		originalPrice: 188000,
		discountRate: 0,
		category: {
			_id: "634d8da516d1688abe54d4f0",
			id: "634d8da516d1688abe54d4f0",
			name: "Phê Bình - Lý Luận Văn Học",
		},
		createdAt: "2022-10-18T16:48:37.436Z",
		updatedAt: "2022-11-23T01:57:15.164Z",
		slug: "nho-giao",
		sold: 99,
		price: 188000,
		countInStock: 7401,
		id: "634ed8e5f6a3a7266d992b0a",
	},
	{
		_id: "634ed8e5f6a3a7266d992bbc",
		name: "Nhà văn và Cuộc sống số 8 (Hội Nhà Văn Việt Nam)",
		description:
			"Nhà văn và Cuộc sống số 8 (Hội Nhà Văn Việt Nam)\nTạp chí Nhà Văn và Cuộc Sống (Hội Nhà Văn Việt Nam)\nTạp chí “Nhà văn &amp; Tác phẩm” đã nhiều lần đổi tên qua các thời kỳ, từ năm 1969 đến năm 1976 tạp chí có tên là “Tác phẩm mới”. Sau lại đổi là “Tạp chí Văn học”, tồn tại từ năm 1988-1989. Từ năm 1990 đến năm 2013, tạp chí có tên là “Tạp chí Nhà văn”. Tháng 7 năm 2013 hợp nhất với tạp chí “Văn học nước ngoài”, đổi thành Tạp chí “Nhà văn &amp; tác phẩm”.\nTuy nhiên, cái tên đã tồn tại trong 7 năm (Từ 2013 cho đến hết năm 2020), hiện nay, cũng không còn thích hợp với tình hình mới nữa. Bởi đã là nhà văn thì phải có tác phẩm rồi. Không có tác phẩm sao gọi là nhà văn. Vậy chữ Tác phẩm thành thừa. Điều cần đặt ra trong tình hình mới bây giờ là sự gắn bó với cuộc sống, đưa hiện thực cuộc sống vào các trang viết sinh động, mới mẻ và sâu sắc. Vì thế, chúng tôi muốn tạp chí có tên mới là NHÀ VĂN &amp; CUỘC SỐNG.Giá sản phẩm trên ToiMuaSach đã bao gồm thuế theo luật hiện hành. Bên cạnh đó, tuỳ vào loại sản phẩm, hình thức và địa chỉ giao hàng mà có thể phát sinh thêm chi phí khác như phí vận chuyển, phụ phí hàng cồng kềnh, thuế nhập khẩu (đối với đơn hàng giao từ nước ngoài có giá trị trên 1 triệu đồng).....",
		translators: "",
		isbn13: "",
		supplier: "Hội Nhà Văn",
		publisher: "Nhà Xuất Bản Hội Nhà Văn",
		publishDate: "2022-03-29T13:06:16.000Z",
		images: [
			"https://salt.tikicdn.com/ts/product/6c/49/61/e62d58e077369cd1a27f59572bdca310.jpg",
		],
		page: null,
		bookCover: "Bìa mềm",
		status: "available",
		originalPrice: 99000,
		discountRate: 0,
		category: {
			_id: "634d8da516d1688abe54d4f0",
			id: "634d8da516d1688abe54d4f0",
			name: "Phê Bình - Lý Luận Văn Học",
		},
		createdAt: "2022-10-18T16:48:37.439Z",
		updatedAt: "2022-11-23T01:57:15.165Z",
		slug: "nha-van-va-cuoc-song-so-8-hoi-nha-van-viet-nam",
		sold: 99,
		price: 99000,
		countInStock: 7401,
		id: "634ed8e5f6a3a7266d992bbc",
	},
];
