# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: REST API CI for ToiMuaSach

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main

jobs:
  build:
    name: Build on node 16
    runs-on: ubuntu-lastest
    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'
        cache: 'npm'
    - name: Install Dependencies
      run: npm i
#     - run: npm ci
#     - run: npm run build --if-present
#     - run: npm test
